new_menus_2 = [
    {
        "탕,찌개": [
            {"name": "송담추어탕", "url": "https://map.naver.com/v5/entry/place/1098724255", "weight": 100},
            {"name": "진대감(파김치전골 등)", "url": "https://map.naver.com/v5/entry/place/33741142", "weight": 100},
            {"name": "삼식이감자탕", "url": "https://map.naver.com/v5/entry/place/37326967", "weight": 100},
            {"name": "수닭도리", "url": "https://map.naver.com/v5/entry/place/1903701644", "weight": 100},
            {"name": "옛날김치찌개", "url": "https://map.naver.com/v5/entry/place/37943649", "weight": 100},
            {"name": "차돌49", "url": "https://map.naver.com/v5/entry/place/36636340", "weight": 100},
            {"name": "전주콩나물국밥", "url": "https://map.naver.com/v5/entry/place/21559094", "weight": 100},
            {"name": "하영호 설렁탕", "url": "https://map.naver.com/v5/entry/place/10985460", "weight": 100},
            {"name": "장금수부대찌개", "url": "https://map.naver.com/v5/entry/place/1858218116", "weight": 100},
            {"name": "순리대로(순대국)", "url": "https://map.naver.com/v5/entry/place/1851351813", "weight": 100},
            {"name": "냉삼식당", "url": "https://map.naver.com/v5/entry/place/1475795053", "weight": 100},
        ]
    },
    {
        "돈까스,일식": [
            {"name": "카츠오우", "url": "https://map.naver.com/v5/entry/place/1003690665", "weight": 100},
            {"name": "강남돈까스", "url": "https://map.naver.com/v5/entry/place/1085467807", "weight": 100},
            {"name": "고씨네(카레)", "url": "https://map.naver.com/v5/entry/place/55737564", "weight": 100},
            {"name": "토라도라(라멘)", "url": "https://map.naver.com/v5/entry/place/1357006951", "weight": 100},
        ]
    },
    {
        "아시안": [
            {"name": "포브라더스", "url": "https://map.naver.com/v5/entry/place/21732929", "weight": 100},
        ]
    },
    {
        "양식": [
            {"name": "리나스파파", "url": "https://map.naver.com/v5/entry/place/37464359", "weight": 50},
            {"name": "퀸즈 블러바드(부리또)", "url": "https://map.naver.com/v5/entry/place/1156931389", "weight": 50},
        ]
    },
    # {
    #     "분식": [
    #
    #     ]
    # },
    {
        "백반,국수": [
            {"name": "사위식당(낙곱새)", "url": "https://map.naver.com/v5/entry/place/1701793098", "weight": 100},
            {"name": "사계솔", "url": "https://map.naver.com/v5/entry/place/34542221", "weight": 100},
            {"name": "명동칼국수", "url": "https://map.naver.com/v5/entry/place/1170151043", "weight": 100},
            {"name": "여민락(쌈밥)", "url": "https://map.naver.com/v5/entry/place/18548850", "weight": 100},
            {"name": "인덕원(비빔국수)", "url": "https://map.naver.com/v5/entry/place/1090964067", "weight": 100},
            {"name": "생연어집(생선구이)", "url": "https://map.naver.com/v5/entry/place/399895808", "weight": 100},
            {"name": "평양면옥", "url": "https://map.naver.com/v5/entry/place/34882345", "weight": 70},
            {"name": "퀸즈 블러바드(부리또)", "url": "https://map.naver.com/v5/entry/place/1156931389", "weight": 50},
        ]
    },
    {
        "중식": [
            {"name": "국빈(알짬뽕)", "url": "https://map.naver.com/v5/entry/place/37417405", "weight": 100},
            {"name": "천향(회사옆 중국집", "url": "https://map.naver.com/v5/entry/place/1300124326", "weight": 100},
        ]
    },
    {
        "패스트푸드": [
            {"name": "버거킹", "url": "https://map.naver.com/v5/entry/place/1374016793", "weight": 100},
            {"name": "풍류랑", "url": "https://map.naver.com/v5/entry/place/1809480572", "weight": 50},
        ]
    },
]

menus = [
    {
        "id": 1,
        "name": "버거킹",
        "url": "https://map.naver.com/v5/entry/place/1374016793",
        "weight": 100,
        "category": 8,
        "weather_category": 1,
        "temperature_category": 3,
        "distance": 131,
        "message": "가까운 곳에서 간단하게, ",
    },
    {
        "id": 2,
        "name": "송담추어탕",
        "url": "https://map.naver.com/v5/entry/place/1098724255",
        "weight": 50,
        "category": 1,
        "weather_category": 1,
        "temperature_category": 1,
        "distance": 53,
        "message": "가까운, ",
    },
    {
        "id": 3,
        "name": "진대감",
        "url": "https://map.naver.com/v5/entry/place/33741142",
        "weight": 100,
        "category": 1,
        "weather_category": 2,
        "temperature_category": 1,
        "distance": 207,
        "message": "파김치전골 맛집, ",
    },
    {
        "id": 4,
        "name": "사위식당",
        "url": "https://map.naver.com/v5/entry/place/1701793098",
        "weight": 80,
        "category": 1,
        "weather_category": 2,
        "temperature_category": 1,
        "distance": 242,
        "message": "오랜만에 낙곱새는 어떠신가요? ",
    },
    {
        "id": 5,
        "name": "사계솔",
        "url": "https://map.naver.com/v5/entry/place/34542221",
        "weight": 100,
        "category": 1,
        "weather_category": 1,
        "temperature_category": 1,
        "distance": 213,
        "message": "순두부찌개, 보쌈정식 맛집. ",
    },
    {
        "id": 6,
        "name": "명동칼국수",
        "url": "https://map.naver.com/v5/entry/place/1170151043",
        "weight": 80,
        "category": 6,
        "weather_category": 2,
        "temperature_category": 2,
        "distance": 320,
        "message": "푸짐하고 만두가 맛있는 ",
    },
    {
        "id": 7,
        "name": "여민락",
        "url": "https://map.naver.com/v5/entry/place/18548850",
        "weight": 90,
        "category": 6,
        "weather_category": 1,
        "temperature_category": 1,
        "distance": 348,
        "message": "쌈채소가 풍부하게 나오는 쌈밥집. ",
    },
    {
        "id": 8,
        "name": "카츠오우",
        "url": "https://map.naver.com/v5/entry/place/1003690665",
        "weight": 80,
        "category": 2,
        "weather_category": 4,
        "temperature_category": 1,
        "distance": 233,
        "message": "언제나 대기가 있는 진짜 맛집! ",
    },
    {
        "id": 9,
        "name": "삼식이감자탕",
        "url": "https://map.naver.com/v5/entry/place/37326967",
        "weight": 80,
        "category": 1,
        "weather_category": 4,
        "temperature_category": 1,
        "distance": 86,
        "message": "항상 줄서 있는 뼈해장국 맛집! ",
    },
    {
        "id": 10,
        "name": "수닭도리",
        "url": "https://map.naver.com/v5/entry/place/1903701644",
        "weight": 90,
        "category": 1,
        "weather_category": 1,
        "temperature_category": 1,
        "distance": 99,
        "message": "닭곰탕, 닭도리탕 어떠신가요? ",
    },
    {
        "id": 11,
        "name": "옛날김치찌개",
        "url": "https://map.naver.com/v5/entry/place/37943649",
        "weight": 100,
        "category": 1,
        "weather_category": 2,
        "temperature_category": 1,
        "distance": 70,
        "message": "회사에서 가까운 김치찌개 맛집. ",
    },
    {
        "id": 12,
        "name": "차돌49",
        "url": "https://map.naver.com/v5/entry/place/36636340",
        "weight": 100,
        "category": 1,
        "weather_category": 1,
        "temperature_category": 1,
        "distance": 130,
        "message": "카페같은 분위기의 한식집. ",
    },
    {
        "id": 13,
        "name": "전주콩나물국밥",
        "url": "https://map.naver.com/v5/entry/place/21559094",
        "weight": 70,
        "category": 1,
        "weather_category": 4,
        "temperature_category": 3,
        "distance": 311,
        "message": "콩나물국밥 말고도 돈까스, 비빔국수가 있는 ",
    },
    {
        "id": 14,
        "name": "국빈",
        "url": "https://map.naver.com/v5/entry/place/37417405",
        "weight": 90,
        "category": 4,
        "weather_category": 2,
        "temperature_category": 1,
        "distance": 223,
        "message": "짬뽕 맛집 ",
    },
    {
        "id": 15,
        "name": "평양면옥",
        "url": "https://map.naver.com/v5/entry/place/34882345",
        "weight": 20,
        "category": 6,
        "weather_category": 1,
        "temperature_category": 3,
        "distance": 352 + 50,
        "message": "정통 평양식 냉면이 나오는 ",
    },
    {
        "id": 16,
        "name": "하영호 설렁탕",
        "url": "https://map.naver.com/v5/entry/place/10985460",
        "weight": 80,
        "category": 1,
        "weather_category": 1,
        "temperature_category": 1,
        "distance": 341 + 50,
        "message": "회사 근처에서 설렁탕을 드신다면 여기로. ",
    },
    {
        "id": 17,
        "name": "포브라더스",
        "url": "https://map.naver.com/v5/entry/place/21732929",
        "weight": 80,
        "category": 5,
        "weather_category": 1,
        "temperature_category": 3,
        "distance": 340 + 50,
        "message": "쌀국수 맛집! ",
    },
    {
        "id": 18,
        "name": "풍류랑",
        "url": "https://map.naver.com/v5/entry/place/1809480572",
        "weight": 20,
        "category": 8,
        "weather_category": 4,
        "temperature_category": 3,
        "distance": 357 + 50,
        "message": "패티에 모든 것을 건 수제버거! ",
    },
    {
        "id": 19,
        "name": "장금수부대찌개",
        "url": "https://map.naver.com/v5/entry/place/1858218116",
        "weight": 70,
        "category": 2,
        "weather_category": 2,
        "temperature_category": 1,
        "distance": 262 + 50,
        "message": "여기서 시킬때는 부대전골 추천~ ",
    },
    {
        "id": 20,
        "name": "강남돈까스",
        "url": "https://map.naver.com/v5/entry/place/1085467807",
        "weight": 70,
        "category": 2,
        "weather_category": 4,
        "temperature_category": 1,
        "distance": 319 + 50,
        "message": "카츠오우에 뒤지지 않는다. ",
    },
    {
        "id": 21,
        "name": "천향",
        "url": "https://map.naver.com/v5/entry/place/1300124326",
        "weight": 50,
        "category": 4,
        "weather_category": 2,
        "temperature_category": 1,
        "distance": 32,
        "message": "회사에서 가장 가까운 ",
    },
    {
        "id": 22,
        "name": "리나스파파",
        "url": "https://map.naver.com/v5/entry/place/37464359",
        "weight": 30,
        "category": 3,
        "weather_category": 4,
        "temperature_category": 3,
        "distance": 107 + 50,
        "message": "파스타는 어때요? ",
    },
    {
        "id": 23,
        "name": "퀸즈 블러바드",
        "url": "https://map.naver.com/v5/entry/place/1156931389",
        "weight": 10,
        "category": 3,
        "weather_category": 4,
        "temperature_category": 3,
        "distance": 331 + 50,
        "message": "부리또, 타코가 생각난다면. ",
    },
    {
        "id": 24,
        "name": "인덕원",
        "url": "https://map.naver.com/v5/entry/place/1090964067",
        "weight": 80,
        "category": 6,
        "weather_category": 4,
        "temperature_category": 3,
        "distance": 173 + 50,
        "message": "비빔국수 맛집. ",
    },
    {
        "id": 25,
        "name": "고씨네",
        "url": "https://map.naver.com/v5/entry/place/55737564",
        "weight": 80,
        "category": 2,
        "weather_category": 1,
        "temperature_category": 1,
        "distance": 360,
        "message": "건더기 없는 일본식 카레집. ",
    },
    {
        "id": 26,
        "name": "생연어집",
        "url": "https://map.naver.com/v5/entry/place/399895808",
        "weight": 80,
        "category": 6,
        "weather_category": 1,
        "temperature_category": 3,
        "distance": 637 + 100,
        "message": "멀지만 또 가고 싶은~ ",
    },
    {
        "id": 27,
        "name": "순리대로",
        "url": "https://map.naver.com/v5/entry/place/1851351813",
        "weight": 90,
        "category": 1,
        "weather_category": 1,
        "temperature_category": 1,
        "distance": 321,
        "message": "순대국 어떠신가요? ",
    },
    {
        "id": 28,
        "name": "냉삼식당",
        "url": "https://map.naver.com/v5/entry/place/1475795053",
        "weight": 90,
        "category": 1,
        "weather_category": 1,
        "temperature_category": 1,
        "distance": 286,
        "message": "찌개, 제육볶음, 생선구이 전부 무난한 ",
    },
    {
        "id": 29,
        "name": "토라도라",
        "url": "https://map.naver.com/v5/entry/place/1357006951",
        "weight": 60,
        "category": 2,
        "weather_category": 4,
        "temperature_category": 1,
        "distance": 501 + 50,
        "message": "라멘 맛집(이라네요) ",
    },
    {
        "id": 30,
        "name": "김가네김밥",
        "url": "https://map.naver.com/v5/entry/place/11760907",
        "weight": 60,
        "category": 7,
        "weather_category": 4,
        "temperature_category": 1,
        "distance": 319,
        "message": "분식은 어떠신가요? ",
    },
    {
        "id": 31,
        "name": "분식문방구",
        "url": "https://map.naver.com/v5/entry/place/1980277788",
        "weight": 60,
        "category": 7,
        "weather_category": 4,
        "temperature_category": 1,
        "distance": 261 + 50,
        "message": "깔끔한 인테리어의 분식집. ",
    },
    {
        "id": 32,
        "name": "알마튜나",
        "url": "https://map.naver.com/v5/entry/place/1625736209",
        "weight": 60,
        "category": 2,
        "weather_category": 1,
        "temperature_category": 1,
        "distance": 310,
        "message": "회덮밥 잘나와요. ",
    }
]

category_enum = [
    {"탕,찌개": 1},
    {"돈까스,일식": 2},
    {"양식": 3},
    {"중식": 4},
    {"아시안": 5},
    {"백반,국수": 6},
    {"분식": 7},
    {"패스트푸드": 8},
]

weather_category_enum = [
    {"날씨안가림": 1},
    {"비,눈가산점": 2},
    # {"눈내리면가산점": 3},
    {"비,눈이면안감": 4}
]

temperature_category_enum = [
    {"기온안가림": 1},
    {"더울때안감": 2},
    {"추울때안감": 3},
]

jey_menu = [
    {"name": "버거킹", "url": "https://map.naver.com/v5/entry/place/1374016793", "weight": 100},
    {"name": "송담추어탕", "url": "https://map.naver.com/v5/entry/place/1098724255", "weight": 100},
    {"name": "진대감(파김치전골 등)", "url": "https://map.naver.com/v5/entry/place/33741142", "weight": 100},
    {"name": "사계솔", "url": "https://map.naver.com/v5/entry/place/34542221", "weight": 100},
    {"name": "카츠오우", "url": "https://map.naver.com/v5/entry/place/1003690665", "weight": 100},
    {"name": "삼식이감자탕", "url": "https://map.naver.com/v5/entry/place/37326967", "weight": 100},
    {"name": "수닭도리", "url": "https://map.naver.com/v5/entry/place/1903701644", "weight": 100},
    {"name": "옛날김치찌개", "url": "https://map.naver.com/v5/entry/place/37943649", "weight": 100},
    {"name": "차돌49", "url": "https://map.naver.com/v5/entry/place/36636340", "weight": 100},
    {"name": "국빈", "url": "https://map.naver.com/v5/entry/place/37417405", "weight": 100},
    {"name": "하영호 설렁탕", "url": "https://map.naver.com/v5/entry/place/10985460", "weight": 100},
    {"name": "포브라더스", "url": "https://map.naver.com/v5/entry/place/21732929", "weight": 100},
    {"name": "풍류랑", "url": "https://map.naver.com/v5/entry/place/1809480572", "weight": 50},
    {"name": "장금수부대찌개", "url": "https://map.naver.com/v5/entry/place/1858218116", "weight": 100},
    {"name": "강남돈까스", "url": "https://map.naver.com/v5/entry/place/1085467807", "weight": 100},
    {"name": "천향", "url": "https://map.naver.com/v5/entry/place/1300124326", "weight": 100},
    {"name": "리나스파파", "url": "https://map.naver.com/v5/entry/place/37464359", "weight": 50},
    {"name": "퀸즈 블러바드(부리또)", "url": "https://map.naver.com/v5/entry/place/1156931389", "weight": 50},
    {"name": "인덕원(비빔국수)", "url": "https://map.naver.com/v5/entry/place/1090964067", "weight": 100},
    {"name": "고씨네(카레)", "url": "https://map.naver.com/v5/entry/place/55737564", "weight": 100},
    {"name": "생연어집(생선구이)", "url": "https://map.naver.com/v5/entry/place/399895808", "weight": 100},
    {"name": "순리대로(순대국)", "url": "https://map.naver.com/v5/entry/place/1851351813", "weight": 100},
    {"name": "냉삼식당", "url": "https://map.naver.com/v5/entry/place/1475795053", "weight": 100},
]
